language: csharp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode9.4

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
    - DOTNET_CLI_TELEMETRY_OPTOUT=1

mono: latest
dotnet: 2.1.502
install:
  - dotnet restore -p:TravisCI=true;Sign=false
script:
  - dotnet test -c:Release -f:netcoreapp2.1 -p:TravisCI=true;Sign=false
